name: bot

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours auto-refresh to stay alive

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot telebot pymongo asyncio requests pyTelegramBotAPI schedule

    - name: Run Telegram bot
      run: |
        echo "Bot is starting..."
        nohup python bot.py &
        sleep 999999
        
